###################################### Base image ######################################

FROM arangodb:3.12.0.2

###################################### ENV & ARG  ######################################

ARG wiki_lang

ENV ARANGO_VERSION 3.9.2
ENV ARANGO_NO_AUTH 1
ENV WIKI_LANG=$wiki_lang

RUN apk update &&\
    apk upgrade &&\
    apk add bash
RUN curl -fsSL https://bun.sh/install | bash 

RUN bun i

EXPOSE 8529 9229

CMD bun run index.ts