networks:
  web:
    name: web
    external: true

services:
  redis-cache:
    image: "redis:alpine"
    container_name: "redis-cache"
    command: redis-server --maxmemory 5gb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    networks:
      - web
