FROM node:22.3.0-alpine3.20 AS node

###################################### Base image ######################################

ARG wiki_lang

ENV WIKI_LANG=$wiki_lang

###################################### ENV & ARG  ######################################

COPY /usr/lib/memgraph/memgraph /usr/lib/memgraph/memgraph

COPY /var/lib/memgraph /var/lib/memgraph

COPY /project/serverless-docker-memgraph /project

WORKDIR /project

RUN npm i

RUN npm run build

CMD npm start