name: Generate Docker image for GCP cloud run API

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2.1.4
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }} 
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v2.1.3
      - name: Create a Google Compute Engine instance to do the work
        run: |
          docker build -t serverless-wiki-graph-api-neo4j -f ./serverless-docker/dockerfile.neo4j ./serverless-docker &&\
          docker tag serverless-wiki-graph-api-neo4j europe-docker.pkg.dev/wikiadventure/wiki-graph/serverless-wiki-graph-api-neo4j &&\
          docker tag serverless-wiki-graph-api-neo4j sacramentix1225/serverless-wiki-graph-api-neo4j &&\
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  &&\
          docker push sacramentix1225/serverless-wiki-graph-api-neo4j &&\
          gcloud auth configure-docker europe-docker.pkg.dev --quiet &&\
          docker push europe-docker.pkg.dev/wikiadventure/wiki-graph/serverless-wiki-graph-api-neo4j
          
