name: Gen Compute GCP Docker image

on:
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2.1.4
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v2.1.3
      - name: Create a Google Compute Engine instance to do the work
        run: |
          docker build -t generate-wiki-rust-graph -f dockerfile . &&\
          docker tag generate-wiki-rust-graph europe-docker.pkg.dev/wikiadventure/wiki-graph/generate-wiki-rust-graph &&\
          docker tag generate-wiki-rust-graph sacramentix1225/generate-wiki-rust-graph &&\
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin &&\
          docker push sacramentix1225/generate-wiki-rust-graph &&\
          gcloud auth configure-docker europe-docker.pkg.dev --quiet &&\
          docker push europe-docker.pkg.dev/wikiadventure/wiki-graph/generate-wiki-rust-graph
          
