name: Generate ${{ github.event.inputs.WIKI_LANG }}wiki arangodump on Google Cloud

on:
  workflow_dispatch:
    inputs:
      WIKI_LANG:
        description: 'The 2 letter lang code to generate dump for'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
            credentials_json: '${{ secrets.GCP_JSON_NON_ESCAPED }}'
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.6.0
      - name: Create a Google Compute Engine instance to do the work
        run: |
          gcloud compute instances create-with-container generate-${{ github.event.inputs.WIKI_LANG }}wiki-graph --project=sixdegreesofwikiadventure \
          --zone=europe-west9-a --machine-type=n2-standard-8 --network-interface=network-tier=PREMIUM,subnet=default \
          --maintenance-policy=MIGRATE --provisioning-model=STANDARD \
          --service-account=six-degrees-of-wiki-adventure@sixdegreesofwikiadventure.iam.gserviceaccount.com \
          --scopes=https://www.googleapis.com/auth/cloud-platform \
          --tags=http-server,https-server --image=projects/cos-cloud/global/images/cos-stable-97-16919-103-16 \
          --boot-disk-size=250GB --boot-disk-type=pd-ssd --boot-disk-device-name=generate-wiki-graph \
          --container-image=docker.io/sacramentix1225/generate-wiki-graph:latest --container-restart-policy=always \
          --container-privileged --container-mount-host-path=host-path=/var/run/docker.sock,mode=rw,mount-path=/var/run/docker.sock \
          --container-env=^,@^GCP_JSON=${{ secrets.GCP_JSON }},@WIKI_LANG=${{ github.event.inputs.WIKI_LANG }} \
          --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring \
          --labels=container-vm=cos-stable-97-16919-103-16
