name: Launch Graph gen on GCP compute engine and deploy to cloud run

on:
  workflow_dispatch:
    inputs:
      WIKI_LANG:
        description: 'The 2 letter lang code to generate dump for'
        required: true
jobs:
  start_compute_engine:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.4
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v2.1.3
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '24.x'
      - name: Run LaunchComputeToLowCarbonFootprintEurope script
        env:
          WIKI_LANG: ${{ github.event.inputs.WIKI_LANG }}
          GCP_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: npx ts-node .github/workflows/LaunchComputeToLowCarbonFootprintEurope.ts
